### ISSUE TITLE
Override the "get app" message

### ISSUE THREAD

**Issue by Sheraff** [rsms/fb-mac-messenger#112]
I do not have a smartphone and this message is just being annoying. I know it's an official thing but just CSSing it out of the way would be cool.
![screen shot 2015-04-26 at 13 12 12](https://cloud.githubusercontent.com/assets/1325721/7336954/f529edb0-ec15-11e4-823a-05a348874e9d.png)

**Comment by rsms** [comment]
I'm surprised they don't offer a way to dismiss it.

Does it reappear after you click "Get App" (and allow the target website to fully load while being signedin to Facebook?) Having previously worked at Facebook myself I know some of these "banners" are recorded as "seen" and then not shown again, or only shown after some amount of time.

If that doesn't fixes it for you, grab the source and build a debug version of the app and use that — debug builds load a local main.js (rather than the common one from a web server), allowing you to make local modification to main.js. You could simply add some code to hide the "banner."
