### ISSUE TITLE
Missing messages when computer comes out of sleep

### ISSUE THREAD

**Issue by kirstein** [rsms/fb-mac-messenger#121]
Missing conversations occur when you close the computer and keep on messaging on other devices. Maybe do a full refresh after coming out of sleep?

**Comment by rsms** [comment]
This is an issue with messenger.com (if really an issue, because I can't repro and I use Messenger on a daily basis)

If you try using messenger.com in Safari for a few days, let us know what happens when you come out of sleep.

Also, what do you mean with "missing" messages? Do they never appear, even when new messages arrive in the same conversation, or do you stop getting messages entirely after waking your computer up?

What OS version?

Closing for now as I don't think this is an issue with this app itself. Feel free to prove me wrong :)
