### ISSUE TITLE
Can't view message timestamps

### ISSUE THREAD

**Issue by deusy** [rsms/fb-mac-messenger#155]
On messenger.com, secondary clicking a message (with two fingers) shows the time at which the message was sent. This app only provide the choice to reload or go back/forward when secondary clicking.

**Comment by rsms** [comment]
It seems to be a WebView issue — disabling JS injections (including not loading the main.js file) causes the same behaviour as in the released version of the app. This might be due to either an issue in how events enter the WebView, and/or how messenger.com does feature-detection (which might succeed in Safari, but fail in this app's webview)

**Comment by sethk** [comment]
#178 should also fix this.

**Comment by rsms** [comment]
Fixed by #178
