### ISSUE TITLE
Assigning to 'id<WebPolicyDelegate>' from incompatible type 'AppDelegate*const __strong'

### ISSUE THREAD

**Issue by cwRichardKim** [rsms/fb-mac-messenger#189]
Just cloned the app and tried to build to get this error.  Running XCode 7.0 on OSX 10.11 Beta (15A279b

![image](https://cloud.githubusercontent.com/assets/5778691/9912071/88ff47e2-5c73-11e5-8a9d-7bf8f77807f7.png)

**Comment by rsms** [comment]
You're targeting 10.11 where the WebKit API introduces breaking changes, in this case the noted protocol problems are due to WebPolicyDelegate, WebFrameLoadDelegate, and WebUIDelegate becoming protocols (they are interfaces in <=10.10.)

You either have to declare the protocol adherence for AppDelegate or—what I would recommend—build for 10.10 instead of 10.11 (i.e. the SDK used.)

Today and in the future this project aims to build for the current (as in stable) version of OS X and related dev tools. Pre-release/beta versions will not be explicitly supported.

**Comment by cwRichardKim** [comment]
great, thanks for the quick response

**Comment by cwRichardKim** [comment]
actually, my deployment target is 10.10

![image](https://cloud.githubusercontent.com/assets/5778691/9913295/290d4526-5c7a-11e5-9697-450bbb4d0333.png)
![image](https://cloud.githubusercontent.com/assets/5778691/9913311/3a0df33e-5c7a-11e5-8fe1-93e96c7d512d.png)

Am i missing something else?

**Comment by rsms** [comment]
Weird.
Well, what's going on is that the version of WebKit (actually, the headers that Xcode uses) are of a different version than those of <=10.10. What causes this on your pre-release setup? I have no idea.

I'm about to try building the project with Xcode 7 (still using 6 for some unrelated reasons.)
Have looked through WebKit headers on 10.10 and there are unfortunately no macros that we could use to conditionally declare protocol adherence for AppDelegate (as doing so unconditionally currently breaks the build on 10.10 SDK.)

**Comment by rsms** [comment]
[FTR] d4e62529ecc28dcc206bd84820ee782e15c26cef introduces macro for conditionally specifying protocol adherence https://github.com/rsms/fb-mac-messenger/blob/d4e62529ecc28dcc206bd84820ee782e15c26cef/Messenger/AppDelegate.h#L5
