### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by wizonesolutions** [rsms/fb-mac-messenger#202]
I want to create an app password. I told Facebook the application was called Messenger, but it didn't accept the password. My email address is correct.

**Comment by bradreardon** [comment]
Facebook App Passwords may not work here, since this is technically just a modified WebView that shows the official messenger.com. They may not accept app passwords on their own services.

Rest assured, there should be no concern in using your real password on this application. You can examine the source yourself and see that no harmful code is injected that will phish your passwords.

**Comment by rsms** [comment]
@bradreardon +1
