### ISSUE TITLE
Icons are not retina ready.

### ISSUE THREAD

**Issue by CristianMoisei** [rsms/fb-mac-messenger#213]
None of the icons throughout the app have a 2x version for the retina version.

**Comment by sfcgeorge** [comment]
The app just wraps Facebook's [web Messenger](https://www.messenger.com) so unfortunately this app can't fix it as the problem is on Facebook's side. I suggest you "Report a Problem" from within messenger by clicking the cog in the top left—that will go to Facebook so hopefully they will fix it. The more people who do this the more likely it will get fixed :)

**Comment by CristianMoisei** [comment]
But messenger.com does have retina icons. They only recently introduced them but they are there.

Also, any word on not being able to move the window under el cap?

Thanks.

**Comment by sfcgeorge** [comment]
Oh, it doesn't for me. I'm guessing they're gradually testing and rolling out the Retina icons then. Hopefully eventually you'll get the Retina version if you do "Messenger > Reload App From Server"

The beta works for me on 10.11 http://fbmacmessenger.rsms.me/dist/Messenger-dev.zip

**Comment by CristianMoisei** [comment]
I will try both of those, thank you.

**Comment by sfcgeorge** [comment]
Retina icons have showed up for me :D it's looking great now. So try reloading the app again, I assume FB will roll it out to everyone soon. But this issue can be closed now I think.
