### ISSUE TITLE
Notification Center intergration

### ISSUE THREAD

**Issue by Raldian** [rsms/fb-mac-messenger#304]
Make it so you can write in the Notification so you don't have to open the app to send a new message.

**Comment by rsms** [comment]
This is really hard to build because it would mean deeply integrating with messenger.com, which won't happen until either Facebook decides to support this app and/or provide a public JS API in messenger.com, or someone spending an hour every week until the end of times updating hacky integration code (Facebook releases new versions of their web at least once a week and a large portion of the JS, CSS and HTML are generated.)

In a perfect would, this feature would be cool, but I don't see how it could be done today. Please, prove me wrong :)
