### ISSUE TITLE
Freezing / very slow text entry in input box.

### ISSUE THREAD

**Issue by kirtan** [rsms/fb-mac-messenger#336]
Only seeing for certain threads. (Ex: http://m.me/united)

**Comment by rsms** [comment]
I've noticed this too for a specific conversation (with a Facebook Page, not a person.) It seems to be an issue with the javascript this app injects to make keyboard shortcuts work that interferes with some recent change to messenger.com

A patch to [https://github.com/rsms/fb-mac-messenger/blob/master/website/app/main.js](main.js) that fixes the issue would be great.

**Comment by rsms** [comment]
Note to whoever digs into this: Seems to be an issue only with conversation with Pages (e.g. a company)

**Comment by chrismessina** [comment]
+1 — seeing this too. Maybe a bot-related issue?

**Comment by rsms** [comment]
The "bot-related issue": https://analytics.facebook.com/blog/bots-for-messenger-adding-analytics-and-fbstart-program/

**Comment by rsms** [comment]
Turns out it was due to some javascript meant to work around the audible bell heard when typing a first character into the message composer. The way Messenger.com is built, it relies on a text input event bubbling past document and that the browser ignores the event (messenger.com code uses the event, but fails to stop it's propagation.) This app is basically a web browser, but it doesn't "catch all" keyboard events that bubble through (instead it passes them up the native view hierarchy and eventually the system triggers the audible bell as an indication that nothing handled the keyboard event.)

The fix is to catch all keyboard events bubbling up to the native code, out from the webview, and simply doing nothing.

**Comment by rsms** [comment]
Released with [version 0.1.10](https://fbmacmessenger.rsms.me/#releases)
