### ISSUE TITLE
Desktop notification setting not persistent

### ISSUE THREAD

**Issue by dapetcu21** [rsms/fb-mac-messenger#37]
Reopening the app resets the desktop notifications setting to off

**Comment by rsms** [comment]
Known issue. Seems to be an issue with the Messenger.com code.

**Comment by rsms** [comment]
Help wanted.
- Why is the notifications state retained _sometimes_ and not always or never?
- How do we make the state (Preferences > "Turn {on,off} desktop notifications") persistent? LocalStorage is enabled and messenger.com is using it (investigate via dev console.) 
- How do we reliably enable desktop notifications on first launch, given we resolve state persistence issues?

Pointers:
- The directory `js-env-research` contains a list of JS files downloaded and "un-minified" from messenger.com — these might have changed since they were downloaded.
- In the aforementioned dir, beautify.sh is a script that uses uglifyjs (`npm install -g uglifyjs`) to pretty-print all .js files in that directory.
- Grep on `desktopNotifsEnabled` to get started
