### ISSUE TITLE
When I trying login , two-step verify gots blank.

### ISSUE THREAD

**Issue by stevenho0811** [rsms/fb-mac-messenger#414]
When I downloaded latest version of messenger, then I typing my account and password, Facebook needs my two-step verify, and I pressed continue, pop-up a browser of Facebook timeline (Mobile version), then nothing happened.

![screen shot 2017-10-25 at 2 19 43 pm](https://user-images.githubusercontent.com/4948562/31983474-f86a886e-b98f-11e7-8617-66c296de7740.png)

Messenger turn into blank page.

![screen shot 2017-10-25 at 2 22 16 pm](https://user-images.githubusercontent.com/4948562/31983453-ebec95a0-b98f-11e7-9588-abf436492cde.png)

OS: 10.12.6
Messenger: 0.1.13

**Comment by gsamat** [comment]
I do experience this issue too. For the record — some facebook URL get's opened in the background default OS browser and redirected to the facebook.com/

**Comment by andygmorris** [comment]
Same here. Signing in to a 2-Step Verification account tells me that I need to verify my facebook account. Clicking continue attempts to load a URL which then immediately redirects (perhaps due to incorrect URL) back to https://m.facebook.com/home.php?_rdr and leaves the app with a blank canvas.

<img width="912" alt="screen shot 2017-11-15 at 2 41 06 pm" src="https://user-images.githubusercontent.com/951393/32824340-2fcf2e70-ca13-11e7-9b4f-30f563da7902.png">

<img width="912" alt="screen shot 2017-11-15 at 2 43 47 pm" src="https://user-images.githubusercontent.com/951393/32824434-8b4ad15a-ca13-11e7-978a-b250e188677d.png">

For reference:
Messenger v0.1.13.1491443794
macOS 10.13.1
Default browser: Chrome (not Safari)
Chrome is already logged into the same account that I'm trying to access via the app.

@rsms 
If you have a fix for this, and need a tester, let me know.

**Comment by zulhfreelancer** [comment]
Same problem here.

**Comment by brendanmullan** [comment]
I had the same issue. Temp fix is:

After getting the blank screen open FB on your phone / desktop and go to the notification that says "**An unrecognised device recently attempted to access your account. Let us know if it was you.**"

Approve the access and click 'save this browser'

Next click on the Messenger app, go to 'Messenger' in the menu bar and click '**Reload app from server**' or press CMD + R.

Should load the chats.
